version: "3"
services:
  neo4j:
    image: neo4j
    hostname: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
      - ./.bin/app/download:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: none
