name: Reset-IMDB-graph

on: workflow_dispatch

env:
  APP_DB_RESET_CMD: "./current/bin/app truncate"
  APP_DB_LOAD_CMD: "./current/bin/app load"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Truncate neo4j
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_SSH_HOST }}
        username: ${{ secrets.CI_SSH_LOGIN }}
        password: ${{ secrets.CI_SSH_PASSWORD }}
        port: 22
        script: ${{ env.APP_DB_RESET_CMD }}

    - name: Fill neo4j
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CI_SSH_HOST }}
        username: ${{ secrets.CI_SSH_LOGIN }}
        password: ${{ secrets.CI_SSH_PASSWORD }}
        port: 22
        script: ${{ env.APP_DB_LOAD_CMD }}